GetVersion = "get_version"
GetNetwork = "get_network"
GetNonce = "get_nonce"
GetTopoheight = "get_topoheight"
GetAddress = "get_address"
SplitAddress = "split_address"
Rescan = "rescan"
GetBalance = "get_balance"
HasBalance = "has_balance"
GetTrackedAssets = "get_tracked_assets"
GetAssetPrecision = "get_asset_precision"
GetTransaction = "get_transaction"
BuildTransaction = "build_transaction"
ListTransactions = "list_transactions"
IsOnline = "is_online"
SetOnlineMode = "set_online_mode"
SetOfflineMode = "set_offline_mode"
SignData = "sign_data"
EstimateFees = "estimate_fees"

# Interact with wallet encrypted database
GetMatchingKeys = "get_matching_keys"
GetValueFromKey = "get_value_from_key"
Store = "store"
Delete = "delete"
HasKey = "has_key"
QueryDB = "query_db"