GetInfo = "get_info"
GetVersion = "get_version"
GetHeight = "get_height"
GetTopoheight = "get_topoheight"
GetStableheight = "get_stableheight"
GetBlockTemplate = "get_block_template"
GetBlockAtTopoheight = "get_block_at_topoheight"